/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {

    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1" apply true
}



repositories {

    maven("https://maven.fabricmc.net")
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
    maven("https://jitpack.io")
    maven("https://plugins.gradle.org/m2/")
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://maven.devs.beer/")
    maven("https://repo.nexomc.com/releases")
    maven("https://repo.oraxen.com/releases")
    maven("https://repo.xenondevs.xyz/releases")
    maven("https://nexus.phoenixdevt.fr/repository/maven-public/")
    maven("https://repo.auxilor.io/repository/maven-public/")
    maven("https://mvn.lumine.io/repository/maven-public/")
}

val spigotApiVersion = property("org-spigotmc-spigot-api")!!
val adventureVersion = property("adventure_version")!!
dependencies {
    api(project(":TNIL-Paper"))
    api(project(":TNIL-Bukkit"))
    api(project(":TNIL-Core"))
    compileOnly("net.kyori:adventure-text-minimessage:$adventureVersion")
    compileOnly("org.spigotmc:spigot-api:$spigotApiVersion")
}

java {

    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks {
    compileJava {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNIL-Example-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNIL-Example-${project.version}.jar"

        dependencies {
            include(dependency(":TNIL-Paper"))
            include(dependency(":TNIL-Bukkit"))
            include(dependency(":TNIL-Core"))
        }
    }
}

description = "The New Item Library Bukkit"
