/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("java")
    id("maven-publish")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("fabric-loom") version "1.6-SNAPSHOT" apply false
    id("org.cadixdev.licenser") version "0.6.1" apply false
}

subprojects {

    apply(plugin = "java-library")
    apply(plugin = "java")
    apply(plugin = "com.github.johnrengelman.shadow")
    apply(plugin = "org.cadixdev.licenser")
    apply(plugin = "maven-publish")

    repositories {
        mavenCentral()
        maven("https://maven.fabricmc.net")
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
        maven("https://oss.sonatype.org/content/repositories/snapshots/")
        maven("https://jitpack.io")
        maven("https://plugins.gradle.org/m2/")
        maven("https://repo.codemc.io/repository/maven-public/")
    }

    dependencies {
        implementation("com.googlecode.json-simple:json-simple:1.1.1") {
            exclude("junit", "junit")
        }
        implementation("com.vdurmont:semver4j:3.1.0")
    }

    tasks {
        compileJava {
            options.encoding = "UTF-8"

            sourceCompatibility = "17"
            targetCompatibility = "17"
        }

        jar {
            from("../license.md")
        }

        shadowJar {
        }

        processResources {
            filesMatching("**/resources/*") {
                expand(rootProject.project.properties)
            }

            outputs.upToDateWhen { false }
        }
    }
}