/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "TNIL"
include(":TNIL-Core")
include(":TNIL-Bukkit")
include(":TNIL-BukkitBase")
include(":TNIL-Paper")
include(":TNIL-Example")
include(":TNIL-Sponge")
project(":TNIL-Core").projectDir = file("Core")
project(":TNIL-Bukkit").projectDir = file("Bukkit")
project(":TNIL-BukkitBase").projectDir = file("BukkitBase")
project(":TNIL-Paper").projectDir = file("Paper")
project(":TNIL-Example").projectDir = file("Example")
