/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {

    `java-library`
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "8.1.1" apply true
}

java {

    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation("com.googlecode.json-simple:json-simple:1.1.1") {
        exclude("junit", "junit")
    }
    implementation("com.vdurmont:semver4j:3.1.0")
}

tasks {
    compileJava {
        sourceCompatibility = "17"
        targetCompatibility = "17"

    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNIL-Core-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNIL-Core-${project.version}.jar"
    }
}

description = "The New Item Library Core"