/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

dependencies {
    api(project(":TNIL-Core"))
    compileOnly("org.spongepowered:spongeapi:8.2.0-SNAPSHOT")
}

repositories {
    maven("https://repo.spongepowered.org/maven")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

description = "The New Item Library Sponge"
