/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("java")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

val spongeApiVersion = property("org-spongepowered-spongeapi")!!

dependencies {
    shadow(project(":TNIL-Core"))
    compileOnly("org.spongepowered:spongeapi:$spongeApiVersion")
}

repositories {
    mavenCentral()
    maven {
        name = "sponge-repo"
        url = uri("https://repo.spongepowered.org/repository/maven-public/")
    }
}

java {

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        enabled = false
    }

    shadowJar {
        archiveFileName = "TNIL-Sponge-${project.version}.jar"

        configurations = listOf(project.configurations.shadow.get())
    }
}

publishing {
    publications {
        create<MavenPublication>("shadow") {
            from(components["java"])
            artifact(tasks["shadowJar"])
        }
    }
    repositories {
        maven("https://repo.codemc.io/repository/maven-releases/")
    }
}

description = "The New Item Library Sponge"
