/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("com.github.johnrengelman.shadow") version "8.1.1" apply true
}

dependencies {
    api(project(":TNIL-Core"))
    compileOnly("org.spigotmc:spigot-api:1.19.4-R0.1-SNAPSHOT")
}

repositories {
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
}

tasks {
    compileJava {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    shadowJar {
        archiveFileName = "TNIL-Bukkit-${project.version}-shadow.jar"

        dependencies {
            include(dependency(":TNIL-Core"))
        }
    }
}

description = "The New Item Library Bukkit"
