/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {

    `java-library`
    `maven-publish`
    id("java")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

repositories {

    maven("https://repo.nexomc.com/releases")
    maven("https://repo.xenondevs.xyz/releases")
    maven("https://repo.oraxen.com/releases")
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

val paperApiVersion = property("io-papermc-paper-paper-api")!!
val nexoVersion = property("com-nexomc-nexo")!!
val novaApiVersion = property("xyz-xenondevs-nova-nova-api")!!
val oraxenVersion = property("io-th0rgal-oraxen")!!

dependencies {
    shadow(project(":TNIL-Core"))
    shadow(project(":TNIL-BukkitBase"))
    compileOnly("io.papermc.paper:paper-api:$paperApiVersion")
    compileOnly("xyz.xenondevs.nova:nova-api:$novaApiVersion")
    compileOnly("com.nexomc:nexo:$nexoVersion")
    compileOnly("io.th0rgal:oraxen:$oraxenVersion")
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNIL-Paper-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNIL-Paper-${project.version}.jar"
        archiveClassifier = ""

        configurations = listOf(project.configurations.shadow.get())
    }
}
publishing {
    publications {
        create<MavenPublication>("shadow") {
            from(components["shadow"])
            groupId = property("tnil_group") as String
            version = property("tnil_version") as String
            artifactId = "TNIL-Paper"
        }
    }
    repositories {
        maven {
            url = uri("https://repo.codemc.io/repository/creatorfromhell/")

            val mavenUsername = System.getenv("GRADLE_PROJECT_MAVEN_USERNAME")
            val mavenPassword = System.getenv("GRADLE_PROJECT_MAVEN_PASSWORD")
            if (mavenUsername != null && mavenPassword != null) {
                credentials {
                    username = mavenUsername
                    password = mavenPassword
                }
            }
        }
    }
}

description = "The New Item Library Paper"
