/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {

    `java-library`
    `maven-publish`
    id("java")
    id("com.gradleup.shadow") version "9.0.0-beta16" apply true
}

repositories {

    maven("https://repo.nexomc.com/releases")
    maven("https://repo.xenondevs.xyz/releases")
    maven("https://repo.oraxen.com/releases")
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

val paperApiVersion = property("io-papermc-paper-paper-api")!!
val nexoVersion = property("com-nexomc-nexo")!!
val novaApiVersion = property("xyz-xenondevs-nova-nova-api")!!
val oraxenVersion = property("io-th0rgal-oraxen")!!

dependencies {
    implementation(project(":TNIL-Core"))
    implementation(project(":TNIL-BukkitBase"))
    compileOnly("io.papermc.paper:paper-api:$paperApiVersion")
    compileOnly("xyz.xenondevs.nova:nova-api:$novaApiVersion")
    compileOnly("com.nexomc:nexo:$nexoVersion")
    compileOnly("io.th0rgal:oraxen:$oraxenVersion")
}

java {

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks {
    compileJava {
        sourceCompatibility = "21"
        targetCompatibility = "21"
    }

    jar {
        dependsOn(shadowJar)
        archiveFileName = "original-TNIL-Paper-${project.version}.jar"
    }

    shadowJar {
        archiveFileName = "TNIL-Paper-${project.version}.jar"

        dependencies {
            include(dependency(":TNIL-BukkitBase"))
            include(dependency(":TNIL-Core"))
        }
    }
}

description = "The New Item Library Paper"
